<?php

namespace Database\Seeders;

use App\Enums\Param\ParamFilterTypeEnum;
use App\Models\Param;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ParamSeeder extends Seeder
{
    public function run(): void
    {
        $items = [
            // ── Основные характеристики одежды ──────────────────────────────────
            [
                'title' => 'Размер',
                'slug' => 'size',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 10,
            ],
            [
                'title' => 'Цвет',
                'slug' => 'color',
                'filter_type' => ParamFilterTypeEnum::COLOR->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => false,
                'sort' => 20,
            ],
            [
                'title' => 'Материал',
                'slug' => 'material',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => true,
                'is_comparable' => true,
                'sort' => 30,
            ],
            [
                'title' => 'Состав',
                'slug' => 'composition',
                'filter_type' => ParamFilterTypeEnum::TEXT->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => true,
                'is_comparable' => true,
                'sort' => 40,
            ],
            [
                'title' => 'Бренд',
                'slug' => 'brand',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => true,
                'is_comparable' => true,
                'sort' => 50,
            ],
            [
                'title' => 'Страна производства',
                'slug' => 'country',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 60,
            ],
            [
                'title' => 'Сезон',
                'slug' => 'season',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 70,
            ],
            [
                'title' => 'Пол',
                'slug' => 'gender',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => false,
                'sort' => 80,
            ],

            // ── Детали и особенности ─────────────────────────────────────────────
            [
                'title' => 'Тип посадки',
                'slug' => 'fit-type',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 90,
            ],
            [
                'title' => 'Длина',
                'slug' => 'length',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 100,
            ],
            [
                'title' => 'Тип рукава',
                'slug' => 'sleeve-type',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 110,
            ],
            [
                'title' => 'Тип горловины',
                'slug' => 'neckline-type',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 120,
            ],
            [
                'title' => 'Застёжка',
                'slug' => 'fastener',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 130,
            ],
            [
                'title' => 'Принт/узор',
                'slug' => 'pattern',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => false,
                'sort' => 140,
            ],
            [
                'title' => 'Стиль',
                'slug' => 'style',
                'filter_type' => ParamFilterTypeEnum::MULTISELECT->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => false,
                'sort' => 150,
            ],

            // ── Уход и свойства ──────────────────────────────────────────────────
            [
                'title' => 'Температура стирки',
                'slug' => 'wash-temp',
                'filter_type' => ParamFilterTypeEnum::INTEGER->value,
                'unit' => '°C',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 160,
            ],
            [
                'title' => 'Можно гладить',
                'slug' => 'can-iron',
                'filter_type' => ParamFilterTypeEnum::BOOLEAN->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 170,
            ],
            [
                'title' => 'Химчистка',
                'slug' => 'dry-clean',
                'filter_type' => ParamFilterTypeEnum::BOOLEAN->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 180,
            ],
            [
                'title' => 'Водонепроницаемость',
                'slug' => 'waterproof',
                'filter_type' => ParamFilterTypeEnum::BOOLEAN->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 190,
            ],
            [
                'title' => 'Ветрозащита',
                'slug' => 'windproof',
                'filter_type' => ParamFilterTypeEnum::BOOLEAN->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 200,
            ],
            [
                'title' => 'Утеплитель',
                'slug' => 'insulation',
                'filter_type' => ParamFilterTypeEnum::STRING->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => true,
                'is_comparable' => true,
                'sort' => 210,
            ],

            // ── Размерные характеристики ─────────────────────────────────────────
            [
                'title' => 'Длина изделия',
                'slug' => 'product-length',
                'filter_type' => ParamFilterTypeEnum::FLOAT->value,
                'unit' => 'см',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 220,
            ],
            [
                'title' => 'Обхват груди',
                'slug' => 'chest-girth',
                'filter_type' => ParamFilterTypeEnum::FLOAT->value,
                'unit' => 'см',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 230,
            ],
            [
                'title' => 'Обхват талии',
                'slug' => 'waist-girth',
                'filter_type' => ParamFilterTypeEnum::FLOAT->value,
                'unit' => 'см',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 240,
            ],
            [
                'title' => 'Обхват бёдер',
                'slug' => 'hip-girth',
                'filter_type' => ParamFilterTypeEnum::FLOAT->value,
                'unit' => 'см',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 250,
            ],
            [
                'title' => 'Длина рукава',
                'slug' => 'sleeve-length',
                'filter_type' => ParamFilterTypeEnum::FLOAT->value,
                'unit' => 'см',
                'is_filterable' => false,
                'is_searchable' => false,
                'is_comparable' => true,
                'sort' => 260,
            ],

            // ── Дополнительные характеристики ────────────────────────────────────
            [
                'title' => 'Коллекция',
                'slug' => 'collection',
                'filter_type' => ParamFilterTypeEnum::STRING->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => true,
                'is_comparable' => false,
                'sort' => 270,
            ],
            [
                'title' => 'Артикул производителя',
                'slug' => 'vendor-code',
                'filter_type' => ParamFilterTypeEnum::STRING->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => true,
                'is_comparable' => false,
                'sort' => 280,
            ],
            [
                'title' => 'Эко-френдли',
                'slug' => 'eco-friendly',
                'filter_type' => ParamFilterTypeEnum::BOOLEAN->value,
                'unit' => null,
                'is_filterable' => true,
                'is_searchable' => false,
                'is_comparable' => false,
                'sort' => 290,
            ],
            [
                'title' => 'Особенности',
                'slug' => 'features',
                'filter_type' => ParamFilterTypeEnum::TEXT->value,
                'unit' => null,
                'is_filterable' => false,
                'is_searchable' => true,
                'is_comparable' => false,
                'sort' => 300,
            ],
        ];

        foreach ($items as $item) {
            Param::updateOrCreate(
                ['slug' => $item['slug']],
                $item
            );
        }
    }
}
